services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'lexicubesdb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'verysecret'
    ports:
      - '3306:3306'
